package edu.rit.swen755.client;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Joanna
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFeedback = new javax.swing.JLabel();
        buttonChooseFile = new javax.swing.JButton();
        textFieldFile = new javax.swing.JTextField();
        labelFile = new javax.swing.JLabel();
        textFieldTeamId = new javax.swing.JTextField();
        textFieldPort = new javax.swing.JTextField();
        textFieldHostname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneFeedback = new javax.swing.JTextPane();
        labelTeamID = new javax.swing.JLabel();
        buttonSubmit = new javax.swing.JButton();
        labelHostname = new javax.swing.JLabel();
        labelPort = new javax.swing.JLabel();
        comboBoxProblem = new javax.swing.JComboBox();
        labelProblem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelFeedback.setText("Feedback from judge:");

        buttonChooseFile.setText("Choose File");
        buttonChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChooseFileActionPerformed(evt);
            }
        });

        textFieldFile.setEditable(false);

        labelFile.setText("File: ");

        textFieldTeamId.setText("1");

        textFieldPort.setText("5109");

        textFieldHostname.setText("localhost");

        textPaneFeedback.setEditable(false);
        jScrollPane1.setViewportView(textPaneFeedback);

        labelTeamID.setText("Team ID:");

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        labelHostname.setText("Hostname:");

        labelPort.setText("Server Port:");

        comboBoxProblem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Problem 1", "Problem 2", "Problem 3", "Problem 4", "Problem 5", " " }));

        labelProblem.setText("Problem:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(labelFeedback)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPort)
                                    .addComponent(labelTeamID)
                                    .addComponent(labelFile)
                                    .addComponent(labelProblem)
                                    .addComponent(labelHostname))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldHostname, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textFieldFile, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonChooseFile))
                                    .addComponent(comboBoxProblem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldTeamId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(buttonSubmit)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHostname)
                    .addComponent(textFieldHostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPort)
                    .addComponent(textFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTeamID)
                    .addComponent(textFieldTeamId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFile)
                    .addComponent(textFieldFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonChooseFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxProblem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProblem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSubmit)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validateValues() {
        boolean valid = true;
        String errorMessage = new String();

        String hostname = textFieldHostname.getText();
        String port = textFieldPort.getText();
        String teamId = textFieldTeamId.getText();
        Object problemId = comboBoxProblem.getSelectedItem();
        if (hostname == null || hostname.trim().isEmpty()) {
            errorMessage = "-Hostname should be provided\n";
            valid = false;
        }
        if (port == null || port.trim().isEmpty()) {
            errorMessage = "-Port address should be provided\n";
            valid = false;
        }
        if (teamId == null || teamId.trim().isEmpty()) {
            errorMessage = "-Team Id should be provided\n";
            valid = false;
        }
        if (problemId == null || problemId.toString().isEmpty()) {
            errorMessage = "-Problem Id should be provided\n";
            valid = false;
        }
        if (lastSelectedFile == null) {
            errorMessage = "-Source code file should be selected\n";
            valid = false;
        }
        if (!valid) {
            JOptionPane.showMessageDialog(this,
                    errorMessage,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

        return valid;
    }

    private void buttonChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChooseFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            lastSelectedFile = fileChooser.getSelectedFile();
            textFieldFile.setText(lastSelectedFile.getName());
        }
    }//GEN-LAST:event_buttonChooseFileActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        if (validateValues()) {
            final String hostname = textFieldHostname.getText();
            final int port = Integer.parseInt(textFieldPort.getText());
            final int teamId = Integer.parseInt(textFieldTeamId.getText());
            final int problemId = Integer.parseInt(comboBoxProblem.getSelectedItem().toString().replace("Problem ", ""));

            Thread sendThread = new Thread(new Runnable() {

                @Override
                public void run() {
                    try {
                        textPaneFeedback.setText("Submitting to server...");
                        TCPConnection connection = new TCPConnection(hostname, port);
                        String feedback = connection.send(lastSelectedFile.getName(), teamId, problemId);
                        textPaneFeedback.setText(feedback);
                    } catch (IOException ex) {
                        ex.printStackTrace();
                        textPaneFeedback.setText("[ERROR] " + ex.getMessage());
                    }
                }
            });
            sendThread.start();
        }
    }//GEN-LAST:event_buttonSubmitActionPerformed

    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    private File lastSelectedFile;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChooseFile;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox comboBoxProblem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFeedback;
    private javax.swing.JLabel labelFile;
    private javax.swing.JLabel labelHostname;
    private javax.swing.JLabel labelPort;
    private javax.swing.JLabel labelProblem;
    private javax.swing.JLabel labelTeamID;
    private javax.swing.JTextField textFieldFile;
    private javax.swing.JTextField textFieldHostname;
    private javax.swing.JTextField textFieldPort;
    private javax.swing.JTextField textFieldTeamId;
    private javax.swing.JTextPane textPaneFeedback;
    // End of variables declaration//GEN-END:variables
}
