#!/bin/bash
rm -f ./tests/*.class
rm -f ./src/*.class
javac tests/*.java src/*.java -cp ./lib/json-simple-1.1.1.jar:./lib/junit-4.12.jar && java -cp ./src/:./tests:./lib/json-simple-1.1.1.jar:./lib/junit-4.12.jar:./lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore $@
