package edu.rit.swen755.faultmonitor;

import javax.swing.JTextArea;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Joanna
 */
public class ConsoleFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConsoleFrame
     */
    public ConsoleFrame() {
        initComponents();
        ((DefaultCaret) textAreaMonitor.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        ((DefaultCaret) textAreaRunningJudge.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        ((DefaultCaret) textAreaSleepingJudge.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMonitor = new javax.swing.JTextArea();
        labelMonitor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaRunningJudge = new javax.swing.JTextArea();
        labelRunJudge = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaSleepingJudge = new javax.swing.JTextArea();
        labelSleepJudge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server output");

        textAreaMonitor.setEditable(false);
        textAreaMonitor.setColumns(20);
        textAreaMonitor.setRows(5);
        jScrollPane1.setViewportView(textAreaMonitor);

        labelMonitor.setText("Monitor Process Output:");

        textAreaRunningJudge.setEditable(false);
        textAreaRunningJudge.setColumns(20);
        textAreaRunningJudge.setRows(5);
        jScrollPane2.setViewportView(textAreaRunningJudge);

        labelRunJudge.setText("Running Judge Process Output:");

        textAreaSleepingJudge.setEditable(false);
        textAreaSleepingJudge.setColumns(20);
        textAreaSleepingJudge.setRows(5);
        jScrollPane3.setViewportView(textAreaSleepingJudge);

        labelSleepJudge.setText("Sleeping Judge Process Output:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMonitor)
                            .addComponent(labelRunJudge)
                            .addComponent(labelSleepJudge))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelMonitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRunJudge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSleepJudge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextArea getTextAreaMonitor() {
        return textAreaMonitor;
    }

    public JTextArea getTextAreaRunningJudge() {
        return textAreaRunningJudge;
    }

    public JTextArea getTextAreaSleepingJudge() {
        return textAreaSleepingJudge;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelMonitor;
    private javax.swing.JLabel labelRunJudge;
    private javax.swing.JLabel labelSleepJudge;
    private javax.swing.JTextArea textAreaMonitor;
    private javax.swing.JTextArea textAreaRunningJudge;
    private javax.swing.JTextArea textAreaSleepingJudge;
    // End of variables declaration//GEN-END:variables
}
